# Generated by Django 4.2.2 on 2023-06-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabustrackerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesyllabus',
            name='syllabus',
            field=models.ManyToManyField(blank=True, limit_choices_to={'isactive': True}, to='syllabustrackerapp.syllabus'),
        ),
    ]
