# Generated by Django 4.2.1 on 2023-06-30 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllabustrackerapp', '0002_alter_coursesyllabus_syllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesyllabus',
            name='day',
            field=models.ForeignKey(limit_choices_to={'isactive': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabustrackerapp.day'),
        ),
    ]
